attack/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('graph.urls'), name='graph'),
]

graph/urls.py
from . import views
from django.conf.urls import url
from django.urls import path

app_name = 'graph'
urlpatterns = [
    path('', views.index, name='index'),
    url(r'^results/$', views.results, name='results'),
    url(r'^results/(?P<device_filter>[a-zA-Z0-9\-_]+)$',
        views.device_results,
        name='device_results'),
]

graph/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime


class Device(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Connection(models.Model):
    device = models.ForeignKey(Device, on_delete=models.CASCADE, related_name='device')
    connected_to = models.ForeignKey(Device, on_delete=models.CASCADE, related_name='connected_to')
    protocol = models.CharField(max_length=100, blank=True, null=True)
    port = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.device.name + ' -> ' + self.connected_to.name


class Node(models.Model):
    device = models.ForeignKey(Device, blank=True, null=True, on_delete=models.CASCADE)
    block = models.SmallIntegerField()
    label = models.CharField(max_length=200)
    DIAMOND = 'diamond'
    ELLIPSE = 'ellipse'
    BOX = 'box'
    SHAPE_CHOICES = (
        (DIAMOND, 'diamond'),
        (ELLIPSE, 'ellipse'),
        (BOX, 'box'),
    )
    shape = models.CharField(
        max_length=10,
        choices=SHAPE_CHOICES,
    )

    def __str__(self):
        return self.label + ', ' + self.shape


class Arrow(models.Model):
    start_block = models.ForeignKey(Node, on_delete=models.CASCADE, related_name='start')
    end_block = models.ForeignKey(Node, on_delete=models.CASCADE, related_name='end')

    def __str__(self):
        return str(self.start_block.block) + ' -> ' + str(self.end_block.block)

graph/views.py
from django.shortcuts import render, redirect
from django.shortcuts import get_list_or_404, get_object_or_404
from django.db.models import Q
from graph.models import Node, Arrow, Device, Connection
from graph.parser import parse_dot, parse_hacl
from graph.graph_gen import pydot

IMG_FILE_PATH = 'graph/static/img/'


def index(request):
    if request.method == 'GET':
        context = {}
        return render(request, 'graph/index.html', context)
    if request.method == 'POST':
        Node.objects.all().delete()
        Arrow.objects.all().delete()
        Device.objects.all().delete()
        Connection.objects.all().delete()

        hacl = request.POST.get('hacl')
        hacl = parse_hacl(hacl)
        for d in hacl:
            device = Device.objects.get_or_create(name=d['device'])[0]
            con = Device.objects.get_or_create(name=d['connected_to'])[0]
            protocol = None if d['protocol'] == '_' else d['protocol']
            port = None if d['port'] == '_' else d['port']
            connection = Connection(device=device,
                                    connected_to=con,
                                    protocol=protocol,
                                    port=port)
            connection.save()

        devices = Device.objects.all().values_list('name', flat=True)
        data = request.POST.get('data')
        data = parse_dot(data)
        for n in data['nodes']:
            node = Node(block=n['block'], label=n['label'], shape=n['shape'])
            for d in devices:
                if d in node.label:
                    node.device = Device.objects.filter(name=d).first()
            node.save()
        for a in data['arrows']:
            s = Node.objects.filter(block=a['start']).first()
            e = Node.objects.filter(block=a['end']).first()
            arrow = Arrow(start_block=s, end_block=e)
            arrow.save()

        return redirect('graph:results')


def results(request):
    if request.method == 'GET':
        devices = Device.objects.all()
        context = {'devices': devices}
        data = {'nodes': {}, 'arrows': []}
        nodes = Node.objects.all()
        for node in nodes:
            arrows = Arrow.objects.filter(start_block=node)
            data['nodes'][node.block] = node
            for arrow in arrows:
                data['arrows'].append(arrow)
        pydot(data)
    return render(request, 'graph/results.html', context)


def device_results(request, device_filter):
    if request.method == 'GET':
        devices = Device.objects.all()
        context = {'device': device_filter, 'devices': devices}

        try:
            data = {'nodes': {}, 'arrows': []}
            device = get_object_or_404(Device, name=device_filter)
            nodes = get_list_or_404(Node, device=device)
            for node in nodes:
                data['nodes'][node.block] = node
                arrows = Arrow.objects.filter(
                    Q(start_block=node) | Q(end_block=node)).all()
                for arrow in arrows:
                    data['arrows'].append(arrow)
            for arrow in data['arrows']:
                if arrow.end_block.block not in data['nodes']:
                    data['nodes'][arrow.end_block.block] = arrow.end_block
            pydot(data)
        except:
            return render(request, 'graph/no_results.html', context)
        return render(request, 'graph/device_results.html', context)



















#

graph/templates/graph/device_results.html
{% load static %}
{% load code_blocks %}

{% header devices %}

<h2>Graph for {{device}}</h2>
<img src="{% static "graph/graph.png" %}" align="left" style="padding-right:20px;">

graph/templates/graph/index.html
<h1>Attack Graph GUI</h1>

<h3>Input your raw data below:</h3>

<form method='POST'>
    <textarea cols='75' rows='20' name='data' placeholder="Paste your .dot data here">
        digraph G {
        	1 [label="1:execCode(fileServer,user):0",shape=diamond];
        	2 [label="2:RULE 3 (remote exploit for a client program):0",shape=ellipse];
        	3 [label="3:accessMaliciousInput(fileServer,victim_3,windows_2003_server):0",shape=diamond];
        	4 [label="4:RULE 22 (Browsing a malicious website):0",shape=ellipse];
        	5 [label="5:attackerLocated(internet):1",shape=box];
        	6 [label="6:hacl(fileServer,internet,httpProtocol,httpPort):1",shape=box];
        	7 [label="7:inCompetent(victim_3):1",shape=box];
        	8 [label="8:hasAccount(victim_3,fileServer,user):1",shape=box];
        	9 [label="9:vulExists(fileServer,'CVE-2010-0812',windows_2003_server,remoteClient,privEscalation):1",shape=box];
        	10 [label="10:execCode(webServer,apache):0",shape=diamond];
        	11 [label="11:RULE 2 (remote exploit of a server program):0",shape=ellipse];
        	12 [label="12:netAccess(webServer,tcp,80):0",shape=diamond];
        	13 [label="13:RULE 6 (direct network access):0",shape=ellipse];
        	14 [label="14:hacl(internet,webServer,tcp,80):1",shape=box];
        	15 [label="15:networkServiceInfo(webServer,httpd,tcp,80,apache):1",shape=box];
        	16 [label="16:vulExists(webServer,'CAN-2002-0392',httpd,remoteExploit,privEscalation):1",shape=box];
        	5 -> 	4;
        	6 -> 	4;
        	7 -> 	4;
        	4 -> 	3;
        	3 -> 	2;
        	8 -> 	2;
        	9 -> 	2;
        	2 -> 	1;
        	14 -> 	13;
        	5 -> 	13;
        	13 -> 	12;
        	12 -> 	11;
        	15 -> 	11;
        	16 -> 	11;
        	11 -> 	10;
        }
    </textarea>
    <textarea cols='75' rows='20' name='hacl' placeholder="Paste your hacl rules here">
        hacl(internet, webServer, tcp, 80).
        hacl(webServer, internet,  _, _).
        hacl(subnet_1, webServer, tcp, _).
        hacl(fileServer, internet, httpProtocol, httpPort).
        hacl(internet, fileServer, httpProtocol, httpPort).
    </textarea>
    </br>
    Warning: This will delete all previously entered data!!!
    </br>
    <input type="submit" value="Submit">
    {% csrf_token %}
</form>

graph/templates/graph/no_results.html
{% load static %}
{% load code_blocks %}

{% header devices %}

<h1>No results found for {{device}}</h1>

graph/templates/graph/results.html
{% load static %}
{% load code_blocks %}

{% header devices %}

<img src="{% static "graph/graph.png" %}" align="left" style="padding-right:20px;">

graph/templates/tags/header.html
<h2>Devices:</h2>
<ul>
    {% for d in devices %}
        <li>
            <a href='{% url 'graph:device_results' d.name %}'>{{d.name}}</a>
        </li>
    {% endfor %}
    <li>
        <a href='{% url 'graph:results' %}'>all_devices</a>
    </li>
</ul>

{% block content %}
{% endblock content %}